### ISSUE TITLE
ClojureScript version fails with "this not defined" in cljs/json_html/core.cljs#L37

### ISSUE THREAD

**Issue by timgilbert** [yogthos/json-html#6]
Hi! I'm trying to get the ClojureScript version of this to work, and am getting an error [on this line in the cljs tree](https://github.com/yogthos/json-html/blob/master/src-cljs/json_html/core.cljs#L37). Looks like this code was copied over from the clojure side, but it doesn't compile cleanly. I tried updating `this` to be `m` which I think would be the same thing in that codebase, but I still wind up getting empty output when I pass a test map into the ClojureScript side of this code.

I also tried, briefly, to port the unit tests from Clojure to ClojureScript, but I found what docs there are on `cemerick.test` to be mostly contradictory and I could never get anything to run correctly, and as far as I can tell there are no official docs for `cljs.test` yet. 

Also your Clojure unit tests are currently failing because they expect a Clojure map {:key "value"} to produce output like `<td>key</td><td>value</td>` but the actual output is more like `<td>:key</td><td>value</td>`.

Anyways, I'm happy to help with this bug but I don't have any more time to do it at the moment. Ideally I'd like to see the Clojure and ClojureScript versions of the codebase merged into a single .cljc file, but I can't find any good documentation on that either. ¯\\\_(ツ)_/¯

**Comment by yogthos** [comment]
I'll definitely take a look, as far as cljc goes, you don't have to do anything special for that. You can see an example of that working in my [markdown-clj](https://github.com/yogthos/markdown-clj/blob/master/project.clj) project. If I get around looking at the bug before you do, I'll let you know. :)

**Comment by yogthos** [comment]
Ok, so `this` and `m` was a typo, I fixed that and pushed out and update. I also got the tests passing. Let me know if stuff works as expected, and if you want to give a shot cljcfying the lib I'd definitely be glad to take a pr for that.

**Comment by yogthos** [comment]
@timgilbert are you still seeing the problem with the latest version or can we close it?

**Comment by timgilbert** [comment]
Thanks for the help, @yogthos. I tried again with `[json-html "0.3.3"]`.

The issue I filed the bug for is fixed, I no longer see a compile error, but I'm still not actually getting any useful hiccup out of the library on the cljs side, all it seems to generate is an empty table.

What I've got in my library now (simplified) is this:

```clojure
(.log js/console "hrm..." (pr-str (json-html/edn->hiccup {:foo :bar :x 1})))
```

...and the log output is this:

```
hrm... [:table.jh-type-object [:tbody ()]]
```

So it seems that the ClojureScript side of things is still broken, though it compiles now.

I'm happy to file a separate ticket for the empty-table output if you'd prefer. (This is the result that originally got me thinking of going down the cljc route, to minimize the code gap between the Clojure and CloureScript sides.)

**Comment by yogthos** [comment]
What version of cljs are you running with, I've made a test project [here](https://github.com/yogthos/json-html-test) and I'm not able to reproduce the problem.

**Comment by timgilbert** [comment]
Hmm, I'm on `[org.clojure/clojurescript "0.0-3211"]` and `[lein-cljsbuild "1.0.6"]`, which look pretty close to your test project's dependencies. I'll try cloning that and messing with it; possibly the problem is somewhere else in my project. I'll update you in this ticket one way or another.

**Comment by yogthos** [comment]
I'm going to close this since it doesn't appear to be a general problem with the library, if you find anything new we can reopen.

**Comment by timgilbert** [comment]
Sounds good, sorry for the late reply. I'll open a new ticket if I can find
a more reproduceable case.
